[package]
name = "fastShow"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
lazy_static = "1.5.0"
libloading = "0.8.8"
slint = "1.11.0"
walkdir = "2.5.0"

[build-dependencies]
slint-build = "1.11.0"
