import { VerticalBox, HorizontalBox, ScrollView, StandardListView  } from "std-widgets.slint";

export struct FileItem {
}

export component MainWindow inherits Window {
    preferred-width: 800px;
    preferred-height: 600px;
    title: @tr("FastShow Image Viewer");

    in-out property<[FileItem]> files;

    VerticalBox {
        HorizontalBox {
        }
        VerticalBox {
        }
    }
}